### ISSUE TITLE
ProcessingPAL doesn't run on MacOS

### ISSUE THREAD

**Issue by David-Hewson** [shashidarette/ProcessingPAL#1]
I've been unable to run your application on my Mac due to an error related to SWT applications. When I run the application by double-clicking it, I get an error message stating the application couldn't run and to check the console for error messages. When I run it using Terminal, I get the following error message:

Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
	no swt-win32-4628 in java.library.path
	no swt-win32 in java.library.path
	Can't load library: /Users/dhewson/.swt/lib/macosx/x86_64/libswt-win32-4628.jnilib
	Can't load library: /Users/dhewson/.swt/lib/macosx/x86_64/libswt-win32.jnilib

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:327)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:236)
	at org.eclipse.swt.internal.C.<clinit>(C.java:16)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:138)
	at UoL.ProcessingPAL.GUI.MainForm.main(Unknown Source)

I think this means the application needs the special VM option -XstartOnFirstThread for SWT applications to run properly on the Mac.

**Comment by shashidarette** [comment]
Thank you @David-Hewson for logging the issue.
It is being looked into and is in progress.

Shashidar

**Comment by shashidarette** [comment]
A ProcessingPAL for Mac is [available](https://github.com/UOL-COLS/ProcessingPAL/releases/tag/V1.1).
